### ISSUE TITLE
网易的玩家管理界面没有保留

### ISSUE THREAD

**Issue by Clat213** [Koud-Wind/Netease-minecraft-LAN-connects-to-Server#1]
按照步骤操作以后，进入游戏发现直接进入了主界面，玩家管理界面直接没有出现

**Comment by Koud-Wind** [comment]
请提供你的目录`\MCLDownload\Game\.minecraft\mods`中的内容

**Comment by Clat213** [comment]
> 请提供你的目录`\MCLDownload\Game\.minecraft\mods`中的内容

我没有安装mod，我尝试启动一个插件服

**Comment by Clat213** [comment]
> > 请提供你的目录`\MCLDownload\Game\.minecraft\mods`中的内容
> 
> 我没有安装mod，我尝试启动一个插件服

所以我的mods文件夹在按照步骤尝试以后是空的

**Comment by Koud-Wind** [comment]
> 所以我的mods文件夹在按照步骤尝试以后是空的

请按照步骤并选择合适的版本安装三位数名称模组
